# Arrays

In [1]:
import array as arr

In [2]:
a=arr.array('i',(1,2,3,4,4))   #Creating an array

In [3]:
a

array('i', [1, 2, 3, 4, 4])

In [4]:
b=arr.array('i',(3,4,5,6,7))

In [5]:
b

array('i', [3, 4, 5, 6, 7])

In [6]:
a[::-1]    #Reverse

array('i', [4, 4, 3, 2, 1])

In [7]:
a[1:]

array('i', [2, 3, 4, 4])

In [8]:
a[2:]

array('i', [3, 4, 4])

In [10]:
a.pop(1)

2

In [11]:
a.remove(1)

In [12]:
a

array('i', [3, 4])

In [13]:
for i in a:
    print(i,end=" ")

3 4 

In [14]:
a+b     #Concatenation

array('i', [3, 4, 3, 4, 5, 6, 7])

# NUMPY

In [15]:
import numpy as np

In [17]:
m=np.array([(1,2,3),(3,4,5,)])
n=np.array([(3,4,5),(6,7,8)])
m

array([[1, 2, 3],
       [3, 4, 5]])

In [18]:
n

array([[3, 4, 5],
       [6, 7, 8]])

In [19]:
m+n

array([[ 4,  6,  8],
       [ 9, 11, 13]])

In [20]:
m-n

array([[-2, -2, -2],
       [-3, -3, -3]])

In [21]:
m%n

array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)

In [22]:
m.ndim

2

In [23]:
m.size

6

In [24]:
m.dtype

dtype('int32')

In [26]:
n.reshape(3,2)

array([[3, 4],
       [5, 6],
       [7, 8]])

In [27]:
n.shape

(2, 3)

In [28]:
n.min()

3

In [29]:
n.max()

8

In [30]:
m.sum()

18

In [31]:
g=np.linspace(1,2,3)

In [32]:
g

array([1. , 1.5, 2. ])

In [34]:
m.sum(axis=0)     #coloumn wise

array([4, 6, 8])

In [35]:
m.sum(axis=1)     #row wise

array([ 6, 12])

In [36]:
np.sqrt(m)

array([[1.        , 1.41421356, 1.73205081],
       [1.73205081, 2.        , 2.23606798]])

In [37]:
np.mean(n)

5.5

In [38]:
m[0,2]

3

In [39]:
m

array([[1, 2, 3],
       [3, 4, 5]])

In [40]:
n.sort()
n

array([[3, 4, 5],
       [6, 7, 8]])

In [41]:
m%n

array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)

In [42]:
m[m>1]

array([2, 3, 3, 4, 5])

In [43]:
m[m!=1]

array([2, 3, 3, 4, 5])