In [3]:
import numpy as np

In [21]:
k=np.array([1,2,3,4,-8,-10])

In [17]:
k

array([  1,   2,   3,   4,  -8, -10])

In [18]:
m=k.astype(float)
m

array([  1.,   2.,   3.,   4.,  -8., -10.])

In [19]:
m[::-1]

array([-10.,  -8.,   4.,   3.,   2.,   1.])